# This file should ensure the existence of records required to run the application in every environment (production,
# development, test). The code here should be idempotent so that it can be executed at any point in every environment.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Example:
#
#   ["Action", "Comedy", "Drama", "Horror"].each do |genre_name|
#     MovieGenre.find_or_create_by!(name: genre_name)
#   end

Quiz.create([
  { question: "What is the highest court in the United States?", options: ["the District Court", "the Supreme Court", "the Appeals Court", "the Federal Court"].to_json, correct_answer: 1 },
  { question: "Who wrote the Declaration of Independence?", options: ["(George) Washington", "(Benjamin) Franklin", "(John) Adams", "(Thomas) Jefferson"].to_json, correct_answer: 3 },
  { question: "What are two Cabinet-level positions?", options: ["Vice President and Secretary of Homeland Security", "Secretary of State and Secretary of Energy", "Secretary of Housing and Urban Development and Secretary of the Interior", "Secretary of Candy and Secretary of Staircase"].to_json, correct_answer: 1 },
  { question: "Who did the United States fight in World War II?", options: ["France and Britain", "Italy and Germany", "Germany and Japan", "China and Russia"].to_json, correct_answer: 2 },
  { question: "Name your U.S. Representative.", options: ["Becca Balint", "John Doe", "Mike Turner", "Jane Smith"].to_json, correct_answer: 0 },
  { question: "Name one war fought by the United States in the 1800s.", options: ["Spanish-American War", "Civil War", "Mexican-American War", "World War I"].to_json, correct_answer: 0 },
  { question: "What do we show loyalty to when we say the Pledge of Allegiance?", options: ["the flag", "the British monarchy", "the Queen", "the Army"].to_json, correct_answer: 0 },
  { question: "What movement tried to end racial discrimination?", options: ["feminist movement", "civil rights movement", "socialist movement", "communist movement"].to_json, correct_answer: 1 },
  { question: "What is the \"rule of law\"?", options: ["Government must obey the law.", "Laws are optional", "Leaders must obey the law.", "Everyone must follow the law."].to_json, correct_answer: 3 },
  { question: "What is one right or freedom from the First Amendment?", options: ["religion", "assembly", "petition the government", "bear arms"].to_json, correct_answer: 0 },
  { question: "What are the two major political parties in the United States?", options: ["Democratic and Republican", "Monarchist and Feudalist", "Liberal and Conservative", "Capitalist and Socialist"].to_json, correct_answer: 0 },
  { question: "When was the Constitution written?", options: ["1492", "1666", "1787", "1812"].to_json, correct_answer: 2 },
  { question: "What does the President's Cabinet do?", options: ["makes laws", "advises the President", "governs states", "declares war"].to_json, correct_answer: 1 },
  { question: "When was the Declaration of Independence adopted?", options: ["May 10, 1775", "April 15, 1789", "July 4, 1776", "June 14, 1801"].to_json, correct_answer: 2 },
  { question: "How old do citizens have to be to vote for President?", options: ["twenty-one (21)", "sixteen (16)", "eighteen (18) and older", "twenty-five (25)"].to_json, correct_answer: 2 },
  { question: "What is one responsibility that is only for United States citizens?", options: ["vote in a federal election", "serve on a jury", "travel abroad", "pay taxes"].to_json, correct_answer: 0 },
  { question: "What does the judicial branch do?", options: ["decides if a law goes against the Constitution", "makes laws", "resolves disputes", "impeaches the President"].to_json, correct_answer: 0 },
  { question: "What are two rights of everyone living in the United States?", options: ["the right to enslave others", "freedom of speech and freedom of religion", "freedom of assembly and the right to bear arms", "freedom to riot and freedom to loot"].to_json, correct_answer: 1 },
  { question: "Name one American Indian tribe in the United States.", options: ["Mohegan", "Oneida", "Vikings", "Cherokee"].to_json, correct_answer: 0 },
  { question: "Who makes federal laws?", options: ["the Supreme Court", "Congress", "Senate and House (of Representatives)", "the Queen of England"].to_json, correct_answer: 1 },
  { question: "What are the two parts of the U.S. Congress?", options: ["the East and West Houses", "the Senate and House (of Representatives)", "the Upper and Lower Houses", "the North and South Houses"].to_json, correct_answer: 1 },
  { question: "Name one war fought by the United States in the 1900s.", options: ["American Revolutionary War", "World War II", "Korean War", "Spanish-American War"].to_json, correct_answer: 1 },
  { question: "Who vetoes bills?", options: ["the Chief Justice", "the President", "the Vice President", "the Speaker of the House"].to_json, correct_answer: 1 },
  { question: "What are two ways that Americans can participate in their democracy?", options: ["run for office and help with a campaign", "overthrow the government", "write to a newspaper and vote", "start a revolution and protest violently"].to_json, correct_answer: 0 },
  { question: "What did the Declaration of Independence do?", options: ["declared our independence (from Great Britain)", "made the USA a monarchy", "said that the United States is free (from Great Britain)", "abolished slavery"].to_json, correct_answer: 0 },
  { question: "What is the political party of the current President?", options: ["Republican", "Democratic", "Independent", "Green Party"].to_json, correct_answer: 1 },
  { question: "What happened at the Constitutional Convention?", options: ["The Founding Fathers wrote the Constitution.", "The American Revolution began", "The Civil War started", "The Bill of Rights was ratified"].to_json, correct_answer: 0 },
  { question: "Who was President during the Great Depression and World War II?", options: ["(Harry) Truman", "(Franklin) Roosevelt", "(Woodrow) Wilson", "(John F.) Kennedy"].to_json, correct_answer: 1 },
  { question: "What is the capital of your state?", options: ["Columbus", "New Islands", "Main City", "State Center"].to_json, correct_answer: 0 },
  { question: "The House of Representatives has how many voting members?", options: ["one thousand (1000)", "four hundred thirty-five (435)", "two hundred (200)", "three hundred sixty-five (365)"].to_json, correct_answer: 1 },
  { question: "If the President can no longer serve, who becomes President?", options: ["the Chief Justice", "the Vice President", "the Secretary of State", "the Senate Majority Leader"].to_json, correct_answer: 1 },
  { question: "Who is in charge of the executive branch?", options: ["the Queen of England", "the President", "the Prime Minister", "the Chief Justice"].to_json, correct_answer: 1 },
  { question: "The Federalist Papers supported the passage of the U.S. Constitution. Name one of the writers.", options: ["(Alexander) Hamilton", "(Thomas) Jefferson", "Publius", "(John) Jay or (James) Madison"].to_json, correct_answer: 0 },
  { question: "We elect a President for how many years?", options: ["ten (10)", "six (6)", "four (4)", "eight (8)"].to_json, correct_answer: 2 },
  { question: "What is the economic system in the United States?", options: ["communist economy", "market economy", "capitalist economy", "socialist economy"].to_json, correct_answer: 2 },
  { question: "Under our Constitution, some powers belong to the federal government. What is one power of the federal government?", options: ["to declare war", "to control religions", "to create an army", "to abolish states"].to_json, correct_answer: 0 },
  { question: "Who signs bills to become laws?", options: ["the Vice President", "the President", "the Chief Justice", "the Speaker of the House"].to_json, correct_answer: 1 },
  { question: "During the Cold War, what was the main concern of the United States?", options: ["Capitalism", "Communism", "Nuclear War", "Fascism"].to_json, correct_answer: 1 },
  { question: "What is freedom of religion?", options: ["You must follow a state-mandated religion", "You can practice any religion, or not practice a religion.", "You cannot have religion", "All religions are banned"].to_json, correct_answer: 1 },
  { question: "Who is the \"Father of Our Country\"?", options: ["(Abraham) Lincoln", "(George) Washington", "(Thomas) Jefferson", "(Benjamin) Franklin"].to_json, correct_answer: 1 },
  { question: "What is the name of the Vice President of the United States now?", options: ["Mike Pence", "Kamala Harris", "Nancy Pelosi", "Chuck Schumer"].to_json, correct_answer: 1 },
  { question: "Why did the colonists fight the British?", options: ["because they wanted to be French subjects", "because of high taxes (taxation without representation)", "because they didn't have self-government", "because the British burned their homes"].to_json, correct_answer: 1 },
  { question: "Name one state that borders Mexico.", options: ["Florida", "New Mexico", "Arizona", "Utah"].to_json, correct_answer: 1 },
  { question: "What did Martin Luther King, Jr. do?", options: ["was a Confederate general", "fought for civil rights", "worked for equality for all Americans", "abolished slavery"].to_json, correct_answer: 1 },
  { question: "Name one branch or part of the government.", options: ["military", "the courts", "legislative", "the presidency"].to_json, correct_answer: 1 },
  { question: "Who is the Chief Justice of the United States now?", options: ["Sonia Sotomayor", "John G. Roberts Jr.", "Brett Kavanaugh", "Amy Coney Barrett"].to_json, correct_answer: 1 },
  { question: "Name one state that borders Canada.", options: ["Texas", "Vermont", "Minnesota", "Kansas"].to_json, correct_answer: 1 },
  { question: "Why does the flag have 13 stripes?", options: ["because there are 13 states", "because there were 13 original colonies", "because the founders liked the number 13", "to represent the 13 amendments"].to_json, correct_answer: 1 },
  { question: "What territory did the United States buy from France in 1803?", options: ["Florida", "Louisiana", "the Louisiana Territory", "California"].to_json, correct_answer: 1 },
  { question: "What did the Emancipation Proclamation do?", options: ["abolished the Constitution", "freed slaves in most Southern states", "freed slaves in the Confederate states", "granted women's suffrage"].to_json, correct_answer: 2 },
  { question: "Name two national U.S. holidays.", options: ["Presidents' Day and Independence Day", "Valentine's Day", "Labor Day and Memorial Day", "St. Patrick's Day and Halloween"].to_json, correct_answer: 0 },
  { question: "Name one U.S. territory.", options: ["Hawaii", "American Samoa", "Puerto Rico", "Alaska"].to_json, correct_answer: 0 },
  { question: "What is one thing Benjamin Franklin is famous for?", options: ["invented the television", "started the first free libraries", "first Postmaster General of the United States", "leader of the American Revolution"].to_json, correct_answer: 2 },
  { question: "How many amendments does the Constitution have?", options: ["fifty (50)", "twenty-seven (27)", "ten (10)", "one hundred (100)"].to_json, correct_answer: 1 },
  { question: "Why do some states have more Representatives than other states?", options: ["because they are more important", "(because) some states have more people", "(because of) the state's population", "because of their economies"].to_json, correct_answer: 1 },
  { question: "Who lived in America before the Europeans arrived?", options: ["Vikings", "American Indians", "Native Americans", "Asians"].to_json, correct_answer: 1 },
  { question: "How many justices are on the Supreme Court?", options: ["12 (twelve)", "9 (nine)", "15 (fifteen)", "7 (seven)"].to_json, correct_answer: 1 },
  { question: "We elect a U.S. Representative for how many years?", options: ["six (6)", "two (2)", "one (1)", "four (4)"].to_json, correct_answer: 1 },
  { question: "Who is one of your state's U.S. Senators now?", options: ["Sherrod Brown", "Brown Jake", "Rob Portman", "Tim Ryan"].to_json, correct_answer: 2 },
  { question: "What is the name of the Speaker of the House of Representatives now?", options: ["Nancy Pelosi", "Kevin McCarthy", "Mitch McConnell", "Chuck Schumer"].to_json, correct_answer: 0 },
  { question: "There are four amendments to the Constitution about who can vote. Describe one of them.", options: ["Only property owners can vote", "Citizens eighteen (18) and older (can vote).", "You don't have to pay (a poll tax) to vote.", "Women cannot vote"].to_json, correct_answer: 1 },
  { question: "What was one important thing that Abraham Lincoln did?", options: ["discovered America", "saved (or preserved) the Union", "led the United States during the Civil War", "abolished the electoral college"].to_json, correct_answer: 1 },
  { question: "Name one right only for United States citizens.", options: ["own property", "vote in a federal election", "run for federal office", "bear arms"].to_json, correct_answer: 1 },
  { question: "What is the name of the national anthem?", options: ["America the Beautiful", "The Star-Spangled Banner", "God Bless America", "Yankees Forever"].to_json, correct_answer: 1 },
  { question: "Who is the Commander in Chief of the military?", options: ["the Secretary of Defense", "the President", "the Joint Chiefs of Staff", "the Senate"].to_json, correct_answer: 1 },
  { question: "What is an amendment?", options: ["a deletion", "a change (to the Constitution)", "an addition (to the Constitution)", "a new law"].to_json, correct_answer: 1 },
  { question: "Who was President during World War I?", options: ["(Franklin) Roosevelt", "(Woodrow) Wilson", "(Theodore) Roosevelt", "(William) McKinley"].to_json, correct_answer: 1 },
  { question: "If both the President and the Vice President can no longer serve, who becomes President?", options: ["the Senate Majority Leader", "the Speaker of the House", "the Secretary of State", "the Chief Justice"].to_json, correct_answer: 1 },
  { question: "What is the capital of the United States?", options: ["New York City", "Washington, D.C.", "Los Angeles", "Chicago"].to_json, correct_answer: 1 },
  { question: "What did Susan B. Anthony do?", options: ["was President of the United States", "fought for civil rights", "fought for women's rights", "ended World War II"].to_json, correct_answer: 2 },
  { question: "What do we call the first ten amendments to the Constitution?", options: ["the Book of Privileges", "the Bill of Rights", "the Supreme Laws", "the Founding Principles"].to_json, correct_answer: 1 },
  { question: "What group of people was taken to America and sold as slaves?", options: ["Irish", "Africans", "Native Americans", "Europeans"].to_json, correct_answer: 1 },
  { question: "When must all men register for the Selective Service?", options: ["at age thirty (30)", "between eighteen (18) and twenty-six (26)", "at age eighteen (18)", "never"].to_json, correct_answer: 2 },
  { question: "What ocean is on the East Coast of the United States?", options: ["Pacific Ocean", "Atlantic Ocean", "Arctic Ocean", "Indian Ocean"].to_json, correct_answer: 1 },
  { question: "Who is the Governor of your state now?", options: ["Kathy Hochul", "Mike DeWine", "Jim Jordan", "Rand Paul"].to_json, correct_answer: 1 },
  { question: "What does the Constitution do?", options: ["abolishes democracy", "protects basic rights of Americans", "defines the government", "creates a dictatorship"].to_json, correct_answer: 1 },
  { question: "In what month do we vote for President?", options: ["May", "November", "March", "September"].to_json, correct_answer: 1 },
  { question: "What is one reason colonists came to America?", options: ["conquest", "political liberty", "escape persecution", "for vacations"].to_json, correct_answer: 1 },
  { question: "Before he was President, Eisenhower was a general. What war was he in?", options: ["World War I", "World War II", "Vietnam War", "Korean War"].to_json, correct_answer: 1 },
  { question: "What ocean is on the West Coast of the United States?", options: ["Atlantic Ocean", "Pacific Ocean", "Southern Ocean", "Indian Ocean"].to_json, correct_answer: 1 },
  { question: "We elect a U.S. Senator for how many years?", options: ["ten (10)", "six (6)", "four (4)", "two (2)"].to_json, correct_answer: 1 },
  { question: "The idea of self-government is in the first three words of the Constitution. What are these words?", options: ["God the Almighty", "We the People", "One Nation", "For the Citizens"].to_json, correct_answer: 1 },
  { question: "Under our Constitution, some powers belong to the states. What is one power of the states?", options: ["declare war", "provide schooling and education", "give a driver's license", "ratify treaties"].to_json, correct_answer: 1 },
  { question: "When do we celebrate Independence Day?", options: ["May 5th", "July 4th", "June 14th", "October 31st"].to_json, correct_answer: 1 },
  { question: "Where is the Statue of Liberty?", options: ["Boston", "Liberty Island", "New York Harbor", "San Francisco"].to_json, correct_answer: 1 },
  { question: "Who was the first President?", options: ["John Adams", "George Washington", "Thomas Jefferson", "Abraham Lincoln"].to_json, correct_answer: 1 },
  { question: "What major event happened on September 11, 2001, in the United States?", options: ["The Civil War ended", "Terrorists attacked the United States.", "World War II began", "The Constitution was signed"].to_json, correct_answer: 1 },
  { question: "Name the U.S. war between the North and the South.", options: ["the American Revolution", "the Civil War", "the War between the States", "the Spanish-American War"].to_json, correct_answer: 1 },
  { question: "What is the name of the President of the United States now?", options: ["Donald Trump", "Joe Biden", "Barack Obama", "George W. Bush"].to_json, correct_answer: 1 },
  { question: "When is the last day you can send in federal income tax forms?", options: ["December 31", "April 15", "June 30th", "September 15th"].to_json, correct_answer: 1 },
  { question: "Name one problem that led to the Civil War.", options: ["foreign invasion", "states' rights", "economic reasons", "disagreement over pizza toppings"].to_json, correct_answer: 1 },
  { question: "What is one promise you make when you become a United States citizen?", options: ["never pay taxes", "serve (the nation if needed)", "defend the Constitution and laws of the United States", "give up loyalty to other countries"].to_json, correct_answer: 1 },
  { question: "What is the supreme law of the land?", options: ["the Bible", "the Constitution", "the Declaration of Independence", "the Magna Carta"].to_json, correct_answer: 1 },
  { question: "Name one of the two longest rivers in the United States.", options: ["Hudson River", "Missouri (River)", "Mississippi (River)", "Colorado River"].to_json, correct_answer: 1 },
  { question: "How many U.S. Senators are there?", options: ["five hundred (500)", "one hundred (100)", "two hundred (200)", "seventy-six (76)"].to_json, correct_answer: 1 },
  { question: "What stops one branch of government from becoming too powerful?", options: ["dictatorship", "separation of powers", "checks and balances", "term limits"].to_json, correct_answer: 2 },
  { question: "Who does a U.S. Senator represent?", options: ["only wealthy citizens", "all people of the state", "the state government", "corporations"].to_json, correct_answer: 1 },
  { question: "There were 13 original states. Name three.", options: ["California, Ohio, Boston", "Pennsylvania, North Carolina and Delaware", "Georgia, South Carolina and New York", "Hawaii, Alaska, Texas"].to_json, correct_answer: 1 },
  { question: "What are two rights in the Declaration of Independence?", options: ["wealth and power", "life and pursuit of happiness", "liberty and life", "freedom from taxes"].to_json, correct_answer: 1 },
  { question: "Why does the flag have 50 stars?", options: ["to represent the 50 founders", "because there are 50 states", "because each star represents a state", "to represent the 50 amendments"].to_json, correct_answer: 2 }
])
